### ISSUE TITLE
How would I use this script to mount more than one gdrive (i.e. personal drive and a shared/team drive)

### ISSUE THREAD

**Issue by oshura3** [BinsonBuzz/unraid_rclone_mount#18]
Hello there,

This looks really amazing! I am just trying to wrap my head around how all of it would work but from the **VERY** limited understanding I have about coding it seems that this would really simplify my life to mount the G-drives and get a jellyfin and/or plex server up and running.

The situation I have is this: I currently have two (maybe more) external hard drives and two separate google drives that I would like to mount together. One of my G drives is my personal drive and one is a shared/team one. I would like my jellyfin/plex docker servers to be able to find the files from both so that I can build a library with them as well as to be able to pull from the local storage I have. I think the end result would be to have a mergerfs mount point with my personal drive, one for my shared drive, and one for all of my local HDDs that jellyfin/plex/etc can read from so that I can access these different containers away from home. Oh and before I forget, I am running all of this off a raspberry pi 4 4gb.

Based on this scenario, would the scripts that you have come up with help me achieve this goal? And if so, what would be the best way to start? I am about to wipe the current SD card I am using in my RPI4 and likely start again so that I can get Nginx proxy manager working along with the other containers I plan on having. Your scripts seem like it would be the way to go.

Thank you for all your work and for reading this.

**Comment by BinsonBuzz** [comment]
If you're trying to merge all the folders into one mount, then you add the
extra folders as extra paths in the mount script options.

If you want more than one mount, then use multiple versions of the script.

If you look at the unraid support thread, similar scenarios are covered.
