### ISSUE TITLE
rclone mount script not working

### ISSUE THREAD

**Issue by nowjon** [BinsonBuzz/unraid_rclone_mount#19]
Hi, I'm trying to move to these scripts from my current RClone config so I can use the Mergerfs but I'm having some issues. 

My rclone config: 

> [bestvillamil]
> type = drive
> client_id = XXX
> client_secret = XXX
> scope = drive
> token = XXX
> root_folder_id = XXX
> 
> [bestvillamilsecure]
> type = crypt
> remote = bestvillamil:secure
> filename_encryption = standard
> directory_name_encryption = true
> password = XXX
> password2 = XXX
> 
> [nowjon]
> type = drive
> client_id = XXX
> client_secret = XXX
> scope = drive
> token = XXX
> root_folder_id = XXX
> 
> [nowjonsharedmedia]
> type = crypt
> remote = nowjon:/PDH/
> filename_encryption = standard
> password = XXX
> password2 = XXX

My current mount script: 

> #!/bin/bash
> #----------------------------------------------------------------------------
> 
> mkdir /mnt/disks/bestvillamil
> mkdir /mnt/disks/bestvillamilsecure
> 
> mkdir /mnt/disks/nowjon
> mkdir /mnt/disks/nowjonsharedmedia
> 
> rclone mount --max-read-ahead 1024k --allow-other -vv --drive-impersonate jonathan@best-villamil.com bestvillamil: /mnt/disks/bestvillamil &
> 
> rclone mount \
> --allow-other \
> --cache-chunk-path=/mnt/cache/appdata/rClone/chunks \
> --cache-dir=/mnt/cache/appdata/rClone/vfs \
> --cache-db-path=/mnt/cache/appdata/rClone/db \
> --cache-info-age=60m \
> --cache-tmp-upload-path=/mnt/cache/appdata/rClone/upload \
> --cache-workers=10 \
> --cache-writes \
> --checkers=10 \
> --dir-cache-time=60m \
> --drive-chunk-size=64M \
> --drive-use-trash=false \
> --fast-list \
> --stats=0 \
> bestvillamilsecure: /mnt/disks/bestvillamilsecure &
> 
> #Nowjon and Shared Storage
> rclone mount --max-read-ahead 1024k --allow-other -vv nowjon: /mnt/disks/nowjon &
> rclone mount --max-read-ahead 1024k --allow-other -vv nowjonsharedmedia: /mnt/disks/nowjonsharedmedia &

The script I edited, this doesn't have enough extra LocalFilesShare's, can I just add more? 

> #!/bin/bash
> 
> ######################
> #### Mount Script ####
> ######################
> ### Version 0.96.7 ###
> ######################
> 
> ####### EDIT ONLY THESE SETTINGS #######
> 
> # INSTRUCTIONS
> # 1. Change the name of the rclone remote and shares to match your setup
> # 2. NOTE: enter RcloneRemoteName WITHOUT ':'
> # 3. Optional: include custom command and bind mount settings
> # 4. Optional: include extra folders in mergerfs mount
> 
> # REQUIRED SETTINGS
> RcloneRemoteName="bestvillamilsecure" # Name of rclone remote mount WITHOUT ':'. NOTE: Choose your encrypted remote for sensitive data
> RcloneMountShare="/mnt/disks/bestvillamilsecure" # where your rclone remote will be located without trailing slash  e.g. /mnt/user/mount_rclone
> LocalFilesShare="/mnt/user/Media/Downloads" # location of the local files and MountFolders you want to upload without trailing slash to rclone e.g. /mnt/user/local. Enter 'ignore' to disable
> MergerfsMountShare="/mnt/disks/merge_bestvillamilsecure" # location without trailing slash  e.g. /mnt/user/mount_mergerfs. Enter 'ignore' to disable
> DockerStart="binhex-jellyfin binhex-plex binhex-emby binhex-delugevpn binhex-jackett sonarr radarr ombi" # list of dockers, separated by space, to start once mergerfs mount verified. Remember to disable AUTOSTART for dockers added in docker settings page
> MountFolders=\{"Downloads/Deluge,Downloads/Deluge/Complete,Downloads/Deluge/Incomplete,Movies,TV Shows,Anime"\} # comma separated list of folders to create within the mount
> 
> # Note: Again - remember to NOT use ':' in your remote name above
> 
> # OPTIONAL SETTINGS
> 
> # Add extra paths to mergerfs mount in addition to LocalFilesShare
> LocalFilesShare2="/mnt/user/Media/Movies" # without trailing slash e.g. /mnt/user/other__remote_mount/or_other_local_folder.  Enter 'ignore' to disable
> LocalFilesShare3="/mnt/user/Media/TV Shows"
> LocalFilesShare4="/mnt/user/Media/Anime"
> 
> # Add extra commands or filters
> Command1="--rc"
> Command2=""
> Command3=""
> Command4=""
> Command5=""
> Command6=""
> Command7=""
> Command8=""
> 
> CreateBindMount="N" # Y/N. Choose whether to bind traffic to a particular network adapter
> RCloneMountIP="10.10.10.10" # My unraid IP is 172.30.12.2 so I create another similar IP address
> NetworkAdapter="eth0" # choose your network adapter. eth0 recommended
> VirtualIPNumber="2" # creates eth0:x e.g. eth0:1.  I create a unique virtual IP addresses for each mount & upload so I can monitor and traffic shape for each of them
> 
> ####### END SETTINGS #######

Here's the log from when it ran 

> 2020/07/26 18:52:34 NOTICE: Encrypted drive 'bestvillamilsecure:': ChangeNotify was unable to decrypt "Scene Naming (Responses)": illegal base32 data at input byte 5
> Script Starting Jul 26, 2020 19:00.01
> 
> Full logs for this script are available at /tmp/user.scripts/tmpScripts/rclone_Mergefs_Mount/log.txt
> 
> 26.07.2020 19:00:01 INFO: Creating local folders.
> 26.07.2020 19:00:01 INFO: *** Starting mount of remote bestvillamilsecure
> 26.07.2020 19:00:01 INFO: Checking if this script is already running.
> 26.07.2020 19:00:01 INFO: Script not running - proceeding.
> 26.07.2020 19:00:01 INFO: *** Checking if online
> 26.07.2020 19:00:07 PASSED: *** Internet online
> 26.07.2020 19:00:07 INFO: Success bestvillamilsecure remote is already mounted.
> 26.07.2020 19:00:07 INFO: Mergerfs already installed, proceeding to create mergerfs mount
> 26.07.2020 19:00:07 INFO: Creating bestvillamilsecure mergerfs mount.
> 26.07.2020 19:00:07 INFO: Adding /mnt/user/Media/Movies to bestvillamilsecure mergerfs mount.
> 26.07.2020 19:00:07 INFO: Adding /mnt/user/Media/TV Shows to bestvillamilsecure mergerfs mount.
> 26.07.2020 19:00:07 INFO: Adding /mnt/user/Media/Anime to bestvillamilsecure mergerfs mount.
> fuse: bad mount point `Shows:/mnt/user/Media/Anime': No such file or directory
> 26.07.2020 19:00:07 INFO: Checking if bestvillamilsecure mergerfs mount created.
> 26.07.2020 19:00:07 CRITICAL: bestvillamilsecure mergerfs mount failed. Stopping dockers.
> binhex-jellyfin
> binhex-plex
> binhex-emby
> binhex-delugevpn
> binhex-jackett
> sonarr
> radarr
> ombi
> Script Finished Jul 26, 2020 19:00.11
> 
> Full logs for this script are available at /tmp/user.scripts/tmpScripts/rclone_Mergefs_Mount/log.txt

Please let me know how I can get this working :)

**Comment by BinsonBuzz** [comment]
It doesn't like the space in:

`LocalFilesShare3="/mnt/user/Media/TV Shows"`
