### ISSUE TITLE
Setting LocalFilesShare to ignore causes a move error

### ISSUE THREAD

**Issue by kajeagentspi** [BinsonBuzz/unraid_rclone_mount#24]
Since LocalFilesShare is not a path the command below generates an invalid path.
https://github.com/BinsonBuzz/unraid_rclone_mount/blob/05689ddfb138c98f61e71596a13eb88e36d6027d/rclone_mount#L61

Therefore, when using the invalid path the command below wont work
https://github.com/BinsonBuzz/unraid_rclone_mount/blob/05689ddfb138c98f61e71596a13eb88e36d6027d/rclone_mount#L211

Logs:

> 05.12.2020 02:40:01 INFO: Not creating local folders as requested.
05.12.2020 02:40:01 INFO: Creating MergerFS folders.
05.12.2020 02:40:01 INFO: *** Starting mount of remote hai
05.12.2020 02:40:01 INFO: Checking if this script is already running.
05.12.2020 02:40:01 INFO: Script not running - proceeding.
05.12.2020 02:40:01 INFO: *** Checking if online
05.12.2020 02:40:02 PASSED: *** Internet online
05.12.2020 02:40:02 INFO: Success hai remote is already mounted.
05.12.2020 02:40:02 INFO: Mergerfs already installed, proceeding to create mergerfs mount
05.12.2020 02:40:02 INFO: Creating hai mergerfs mount.
mv: cannot move '/mnt/user/mount_mergerfs/hai' to 'ignore/hai': No such file or directory
\* ERROR: unable to parse 'branches' - ignore/hai:/mnt/user/mount_rclone/hai
\* ERROR: mountpoint not set
05.12.2020 02:40:02 INFO: Checking if hai mergerfs mount created.
05.12.2020 02:40:02 CRITICAL: hai mergerfs mount failed.  Stopping dockers.
binhex-plexpass
binhex-rtorrentvpn
Script Finished Dec 05, 2020  02:40.02

**Comment by BinsonBuzz** [comment]
Understood - ignore my comment on the commit.

Merged :-)
