### ISSUE TITLE
Duplicate Folders

### ISSUE THREAD

**Issue by TheEscPilot** [BinsonBuzz/unraid_rclone_mount#8]
Hi! I'm running into an issue when I use this script to mount my GDrive inside of Unraid. 

![image](https://user-images.githubusercontent.com/29232045/75784933-f6e15f80-5d30-11ea-8858-25206eddf519.png)

The folders that I'm trying to access in MergerFS seem to be duplicated. So my folder structure used to look like 

/mnt/user/mount_mergerfs/gdrive_vfs/audiobooks
/mnt/user/mount_mergerfs/gdrive_vfs/tv
/mnt/user/mount_mergerfs/gdrive_vfs/movies 
etc

It now appears like 
/mnt/user/mount_mergerfs/gdrive_vfs/audiobooks
/mnt/user/mount_mergerfs/gdrive_vfs/audiobooks
/mnt/user/mount_mergerfs/gdrive_vfs/movies
/mnt/user/mount_mergerfs/gdrive_vfs/movies
/mnt/user/mount_mergerfs/gdrive_vfs/tv
/mnt/user/mount_mergerfs/gdrive_vfs/tv

Whenever I try to ssh into these folders, it will sometimes allow me in (to show me that both folders are identical). Whenever I try deleting or moving the folders, the changes affect my remote storage. 

I've tried renaming my rclone mapping, however the duplication seems to carry over regardless of the name/folder. 

How can I collapse these double folders into a single one? Or just remove one of these mappings so when I try to access /mnt/user/mount_mergerfs/gdrive_vfs/tv it only has 1 option to choose? 

Or is it possible to fully remove any cached data and force rclone to pull down the folder structure from my remote storage? When I run "rclone lsd gdrive_vfs:\" it populates a folder structure with single entries.

My dockers seem to be paralyzed by the choice of accessing 2 identically named folders.

**Comment by BinsonBuzz** [comment]
I'm not sure how you've managed this.  Can you post your rclone config (without passwords) and your mount script on the unraid support forum please:  https://forums.unraid.net/topic/75436-guide-how-to-use-rclone-to-mount-cloud-drives-and-play-files/
